#!/usr/bin/env python3
import re
import os

def parse_gcode_metadata(gcode_path):
    """Extrai metadados completos do G-code (OrcaSlicer, PrusaSlicer, Cura, etc.)"""
    metadata = {
        'print_time': None,
        'filament_used': None,
        'filament_type': None,
        'nozzle_temp': None,
        'bed_temp': None,
        'layer_height': None,
        'infill': None,
        'slicer': None,
        'total_layers': None,
        'filament_density': None,
        'filament_diameter': None,
        'max_z_height': None
    }
    
    try:
        with open(gcode_path, 'r', encoding='utf-8', errors='ignore') as f:
            found_m104 = False
            found_m140 = False
            
            for i, line in enumerate(f):
                if i > 500:
                    break
                
                line = line.strip()
                comment_line = line[1:].strip() if line.startswith(';') else line
                
                if 'generated by' in line.lower():
                    if 'orcaslicer' in line.lower():
                        slicer_match = re.search(r'OrcaSlicer\s+([\d.]+)', line, re.IGNORECASE)
                        if slicer_match:
                            metadata['slicer'] = f"OrcaSlicer {slicer_match.group(1)}"
                
                if 'total layer number' in comment_line.lower():
                    layers_match = re.search(r':\s*(\d+)', comment_line)
                    if layers_match:
                        metadata['total_layers'] = int(layers_match.group(1))
                
                if 'filament_density' in comment_line.lower() and not metadata['filament_density']:
                    density_match = re.search(r':\s*([\d.]+)', comment_line)
                    if density_match:
                        metadata['filament_density'] = float(density_match.group(1))
                
                if 'filament_diameter' in comment_line.lower() and not metadata['filament_diameter']:
                    diameter_match = re.search(r':\s*([\d.]+)', comment_line)
                    if diameter_match:
                        metadata['filament_diameter'] = float(diameter_match.group(1))
                
                if 'max_z_height' in comment_line.lower():
                    z_match = re.search(r':\s*([\d.]+)', comment_line)
                    if z_match:
                        metadata['max_z_height'] = float(z_match.group(1))
                
                if not metadata['print_time']:
                    filename = os.path.basename(gcode_path)
                    time_match = re.search(r'(\d+)m(\d+)s', filename)
                    if time_match:
                        m, s = time_match.groups()
                        metadata['print_time'] = f"{m}m {s}s"
                
                if not metadata['filament_type']:
                    filename = os.path.basename(gcode_path)
                    for material in ['PETG', 'PLA', 'ABS', 'TPU', 'NYLON', 'ASA', 'PC']:
                        if material in filename.upper():
                            metadata['filament_type'] = material
                            break
                
                if not found_m104 and line.startswith('M104'):
                    temp_match = re.search(r'S(\d+)', line)
                    if temp_match:
                        metadata['nozzle_temp'] = int(temp_match.group(1))
                        found_m104 = True
                
                if not found_m140 and line.startswith('M140'):
                    temp_match = re.search(r'S(\d+)', line)
                    if temp_match:
                        metadata['bed_temp'] = int(temp_match.group(1))
                        found_m140 = True
    
    except Exception as e:
        print(f"Erro ao parsear metadados do G-code: {e}")
    
    return metadata

# Testar com o arquivo
metadata = parse_gcode_metadata("/Users/tonymichaelbatistadelima/Downloads/Cubo_PETG_52m31s.gcode")
print("\n=== METADADOS EXTRAÍDOS DO G-CODE ===\n")
for key, value in metadata.items():
    if value is not None:
        print(f"  {key:20s}: {value}")
